### ISSUE TITLE
Upgrade to Rails 5.0

### ISSUE THREAD

**Issue by chrislo** [alphagov/manuals-publisher#1051]
This was mentioned by @boffbowsh during our meeting today.

See https://docs.publishing.service.gov.uk/manual/upgrade-rails.html

**Comment by floehopper** [comment]
A number of other GOV.UK apps have recently been upgraded to Rails v5. It might be worth looking at the relevant PRs to avoid reinventing the wheel, e.g. https://github.com/alphagov/hmrc-manuals-api/pull/174.

**Comment by floehopper** [comment]
Also see https://github.com/alphagov/router-api/pull/106.
