### ISSUE TITLE
Investigate whether note in README about recent MongoDB versions is still relevant

### ISSUE THREAD

**Issue by floehopper** [alphagov/manuals-publisher#1185]
Since the app is now using a much more recent version of Mongoid, I wonder whether [the note in the README](https://github.com/alphagov/manuals-publisher/tree/9758fa26f1c2277e04a80226f2b9f0138bde9695#running-the-application) is still relevant/correct.

**Comment by KludgeKML** [comment]
It isn't - this is now running on Mongo 3.6 on a shared documentdb cluster. I'll update the note.

**Comment by KludgeKML** [comment]
(in fact it's already been removed)

**Comment by floehopper** [comment]
🎉
