### ISSUE TITLE
Remove dependancy on govuk_frontend_toolkit

### ISSUE THREAD

**Issue by alicebartlett** [alphagov/manuals-publisher#273]
This app has a dependancy on govuk_frontend_toolkit which it probably shouldnt have as doesn't and shouldnt have the GOV.UK look and feel as it is an admin app. It is currently only using things like %contain-floats from the govuk_frontend_toolkit so we should remove this dependancy.

**Comment by chrisroos** [comment]
Based on @fofr's comment above and [this comment in the Gemfile](https://github.com/alphagov/manuals-publisher/blob/a80f96cff9945f6d5f03a0e9430c25cda08c17d2/Gemfile#L46) I'm going to close this issue based on the assumption that we'll continue to include the govuk_frontend_toolkit for the foreseeable future.

**Comment by h-lame** [comment]
One reason for keeping govuk_frontend_toolkit is that it makes the markdown previews look more like the content would when published.  This is not just styling, but includes behavioural elements like priority lists.
