### ISSUE TITLE
Problem with govspeak for inline attachments in lists

### ISSUE THREAD

**Issue by fofr** [alphagov/manuals-publisher#620]
(This is mostly a brain dump following some investigation on 2nd line.)

Following the Zendesk ticket https://govuk.zendesk.com/agent/tickets/1210622 it was found that the following govspeak is considered invalid by Specialist Publisher:

```
* [InlineAttachment:DHPC_Drug_shortage_InductOs_GB-NIR_CLEAN_FINAL.pdf]: Some text
```

After some investigation the error seems to happen only when all of the following are true:
- There is a list item that begins with a square bracket `* [`
- There is a closing square bracket immediately followed by a colon and a space: `]:`

Putting a character between the `*` and the `[` works, eg `* .[`. Removing the colon works. Using other characters that might be considered special, such as $ or `.` works fine. It was also noted that `\:` seems to escape the colon.

The shortest syntax that produces this bug is:
`* [a]:` (note the space)

**Comment by chrisroos** [comment]
I've tried to replicate this problem in the integration environment.

* I created a new manual and added `* [InlineAttachment:DHPC_Drug_shortage_InductOs_GB-NIR_CLEAN_FINAL.pdf]: Some text` to the body. 
* I clicked "Preview" and see the following error "Body cannot include invalid Govspeak, invalid HTML, any JavaScript or images hosted on sites except for www-origin.integration.publishing.service.gov.uk, assets-origin.integration.publishing.service.gov.uk, www.gov.uk, assets.digital.cabinet-office.gov.uk, assets.publishing.service.gov.uk"
* I clicked "Save as draft" and see the same error.
* I did the same thing but added the content to the section body and see the same error.

I can't see the original Zendesk ticket (I get a 404) so don't know whether this is the behaviour that was being experienced when it was first investigated.

@fofr: Do you have any more information about this issue that would be useful? Or do you think I can close it?

**Comment by chrisroos** [comment]
I've not heard anything more about this issue so I'm going to close it. @fofr: Feel free to re-open if you think I've closed it in error.
