### ISSUE TITLE
Upgrade Ruby version

### ISSUE THREAD

**Issue by alexmuller** [alphagov/manuals-publisher#786]
Hi!

This is the only application on GOV.UK which is running Ruby 2.1.2. It would be really good to upgrade it so that we can remove that Ruby version.

**Comment by h-lame** [comment]
Wrote this up in our backlog : https://trello.com/c/0eULwcEE/84-upgrade-ruby-version-on-manuals-publisher - is going to 2.1.8 (the latest 2.1.x in https://github.com/alphagov/govuk-puppet/blob/master/modules/govuk_rbenv/manifests/all.pp at time of writing) ok, or is your intention to remove 2.1.x entirely?

**Comment by alexmuller** [comment]
2.1.8 is fine for now, there are a few other things using 2.1.x which infrastructure will take quite a bit of time to remove (like Errbit and EFG). But once those are gone we'll come and bother you again :)
