### ISSUE TITLE
flappy content schema test

### ISSUE THREAD

**Issue by mcgoooo** [alphagov/manuals-publisher#789]
Hey,

just putting a note in for this.

there seems to be some [flaky tests](https://ci.dev.publishing.service.gov.uk/job/govuk_manuals_publisher_schema_tests/1686/) in the manuals publisher that get triggered when you update content schema, looking through the builds it seems to be a common flaky test

**Comment by mcgoooo** [comment]
we owe you a beer :D

**Comment by h-lame** [comment]
Well, my commit message does say "...and the test consistently passes (or so it seems anyway)." so maybe give it a while 😉 to be sure.
