### ISSUE TITLE
Remove Services.publishing_api

### ISSUE THREAD

**Issue by chrisroos** [alphagov/manuals-publisher#809]
As per [@h-lame's comment on PR #798](https://github.com/alphagov/manuals-publisher/pull/798#discussion_r98922123):

> I'd be 100% surprised if we need publishing_api and publishing_api_v2. I suspect we can drop the former, and rename the latter to publishing_api

---

Update 4 Apr 17

We're no longer using v1 of the Publishing API in manuals-publisher so it can be removed. Once removed we should probably rename `Services.publishing_api_v2` to `.publishing_api`.

**Comment by h-lame** [comment]
I am willing to say that the answer here is "no, we don't need to" and (without cheking) that the code is only using v2.  v1 is effectively, if not officially deprecated.

**Comment by floehopper** [comment]
I attempted to remove all use of v1 Publishing API in #832, but did not completely succeed because of #851. If we can fix the latter or remove the relevant script then we should be able to close this issue.

**Comment by chrisroos** [comment]
PR #903 addresses issue #851 and, in doing so, removes the last occurrences of v1 of the Publishing API. If/when PR #903 if merged we should be able to resolve this issue by removing `Services#publishing_api`.

**Comment by chrisroos** [comment]
PR #903 has been merged so I think we can now remove all occurrences of Publishing API v1.

@floehopper: You're currently assigned to this issue. Are you planning to do the work or is it up for grabs for anyone to do?

**Comment by chrisroos** [comment]
@floehopper has confirmed in Slack that he's not actively working on this so I'm going to remove him from this issue.

**Comment by chrisroos** [comment]
I've updated the title now that we know we can remove v1 of the Publishing API from this app.

**Comment by chrisroos** [comment]
I've opened PR #979 to address this issue.

**Comment by chrisroos** [comment]
I've just merged PR #979 which resolves this issue.
