### ISSUE TITLE
Investigate the difference between rendering pipelines of `ManualDocumentRenderer` and `SpecialistDocumentRenderer`

### ISSUE THREAD

**Issue by chrisroos** [alphagov/manuals-publisher#810]
As per [@h-lame's comment on PR #798](https://github.com/alphagov/manuals-publisher/pull/798#discussion_r98923301).

> It feels like it might be a bug that this and the ManualDocumentRenderer you deal with in the next few commits are subtly different; this one doesn't do FootnoteSomethingSomething in its pipeline, but the ManualDocumentRenderer does. We should check obviously, but I think we can get rid of this one and replace it's single use with an instance of the ManualDocumentRenderer instead.

**Comment by chrisroos** [comment]
@chrislo mentioned that he's addressing this in his current branch.

**Comment by chrislo** [comment]
I fixed this in d88b3891 as part of the renaming from `ManualDocument` to `Section`
