### ISSUE TITLE
Fix 'safe' write concern option deprecation

### ISSUE THREAD

**Issue by floehopper** [alphagov/manuals-publisher#823]
The following warning is appearing in the build output:

    [DEPRECATED] The 'safe' write concern option has been deprecated in favor of 'w'

It would be good to fix this to improve the signal-to-noise ratio in the test output.

**Comment by floehopper** [comment]
It looks as if we need mongoid >= v4.0.0 to fix this: https://github.com/mongodb/mongoid/blob/master/CHANGELOG.md#400.

**Comment by chrisroos** [comment]
I don't see this warning in the branch that upgrades us to using Mongoid 3 - PR #929.

**Comment by chrisroos** [comment]
PR #929 has been merged and I'm no longer seeing this warning in master so I'm closing this issue.
