### ISSUE TITLE
Fix or remove reslug_manual_section script

### ISSUE THREAD

**Issue by floehopper** [alphagov/manuals-publisher#851]
We should decide whether or not it's worth keeping this script. If we do decide to keep it, we'll need to fix it and ensure that it remains fixed by adding the appropriate test coverage.

From [this comment][1] by @floehopper:
> The two places which are using v1 of the Publishing API have been broken since [this commit][2], because they rely on methods which were [removed from gds-api-adapters in v38.0.0][3]; the application is currently using v39.2.0. This PR removes a bunch of code around the invocations of these non-existent methods on the basis that the code is currently useless.
>
> [...]
>
> I'm slightly less confident that the `bin/reslug_manual_section` script and its associated code can be removed, but given that it is currently broken, if someone wants to keep it, it will need to be fixed. I would also argue that it should only be kept if we write a test for it to ensure that it stays in a working state.

From [this comment][4] by @h-lame:
> I think you could replace the `put_content_item` call in `PublishingAPIRedirecter` with a call to `put_content` on a publishing_api_v2 adapter.  I'm fairly sure these are equivalent.
> 
> The `bin/reslug_manual_section` script is something we wrote last year in response to a support ticket, and I think we've had to run it more than once (but obvs not since I broke it with a gem bump).  We get a lot of requests to do this kind of thing to HMRC manuals (which live in a different app), and it's conceivable we'd get other requests to do it on these, as you can't change the slug once it's published (I think).
>
> I think it's probably 50:50 on whether we drop that script as you've done already, or fix the underlying thing and add tests.  If we chose to fix it I suspect it would be worth looking at the `ManualRelocator` in lib.  This object works across an entire manual rather than a single section, but it's more recent, and has some tests.  Maybe a good approach would be to remove the `PublishingAPIRedirecter`, and replace it with some functionality extracted from `ManualRelocator`?  I reckon it's up to you as current custodians though, as that sounds like a lot of work.

[1]: https://github.com/alphagov/manuals-publisher/pull/832#issue-213028165
[2]: https://github.com/alphagov/manuals-publisher/commit/11c9cfe237ea3150a3ead96da1c1a349b53d2323
[3]: https://github.com/alphagov/gds-api-adapters/blob/master/CHANGELOG.md#3800
[4]: https://github.com/alphagov/manuals-publisher/pull/832#issuecomment-285357242

**Comment by brenetic** [comment]
This is a useful script for second line on Gov.uk. Would be nice to keep it around. 

As an added extra it would also be nice for it to support re-slugging all sections in a manual if their title and their slug have gotten out of sync. i.e in case a title of `1. Foo Bar` has been slugged as `2-foo-bar` accidentally. As seen in this ticket: https://govuk.zendesk.com/agent/tickets/1908077

**Comment by floehopper** [comment]
It seems as if there are other issues with the script:

From a Slack message by @brenetic who was trying to run the script in integration:

> [...] it's also attempting to call a now private method on a `ContentItem`.

**Comment by brenetic** [comment]
[This PR](https://github.com/alphagov/manuals-publisher/pull/863) fixes the issue in the comment above

**Comment by chrislo** [comment]
I've suggested removing `ManualRelocator` in #878.

**Comment by chrisroos** [comment]
We think this script would be useful in fixing https://govuk.zendesk.com/hc/en-us/requests/1908077.

**Comment by chrisroos** [comment]
This script has been fixed and a test has been added in PR #903. Closing.
