### ISSUE TITLE
Add a rake task to allow manuals to be renamed

### ISSUE THREAD

**Issue by chrislo** [alphagov/manuals-publisher#881]
Arrises from #878

In order to make `ManualRelocator` easier to use and to remind other developers that the code in the class should not be removed we should create a simple rake task that instantiates and calls the class with the command line arguments.

**Comment by floehopper** [comment]
There's also some potentially useful info about this in #851.

**Comment by chrisroos** [comment]
PR #1031 adds a Rake task to allow manuals to be relocated.

**Comment by chrisroos** [comment]
PR #1031 has been merged so I'm closing this issue.
