### ISSUE TITLE
Use MONGODB_URI instead of MONGODB_NODES in mongoid config

### ISSUE THREAD

**Issue by chrisroos** [alphagov/manuals-publisher#930]
It looks as though the standard way of defining multiple MongoDB hosts is to use the `MONGODB_URI` environment variable ([see other alphagov apps using this variable](https://github.com/search?q=org%3Aalphagov+mongodb_uri&type=Code)). Manuals Publisher uses a custom `MONGODB_NODES` environment variable instead because Ruby 2.1 couldn't parse multiple hosts from the `MONGODB_URI`. See the commit note and comments in https://github.com/alphagov/govuk-puppet/commit/0d03bfd5c6e5e875906c9b1a9f44969f6dd2c330 for more information.

Manuals Publisher is now using Ruby 2.2 (see a0aa4406d156ac1f28c9bc4a1f026f28d262c8c4) so it should hopefully be possible to remove `MONGODB_NODES` and switch to using `MONGODB_URI` instead.

**Comment by floehopper** [comment]
I've opened a [PR on govuk-puppet to remove the `MONGODB_NODES` env var](https://github.com/alphagov/govuk-puppet/pull/5698).
