### ISSUE TITLE
Investigate the remove_draft_manual_section script

### ISSUE THREAD

**Issue by chrisroos** [alphagov/manuals-publisher#946]
PR #945 adds information to the README from the ops manual. It references a script named `remove_draft_manual_section` that no longer exists in the app. We need to ensure the information in the README matches the code in the app.

* Should we remove the references to the `remove_draft_manual_section` script from the README? Maybe whatever it was doing can now be done through the UI?
* Should we resurrect the `remove_draft_manual_section` script?
* Should we replace references to the `remove_draft_manual_section` script with references to other, more suitable, scripts?

**Comment by floehopper** [comment]
Maybe the instructions should recommend running the script via Jenkins if that's possible or at least have some way to record the fact that it's been run. Maybe the latter is dependent on #858.

If this is going to be the canonical place for instructions on how to run the various scripts, perhaps it would be worth documenting the other existing ones in some way...?

**Comment by chrisroos** [comment]
This `remove_draft_manual_section` script was removed in 654ca53b35be6c3b547df1be8f3e2e5518e31ec6. That commit note explains that the functionality is now available in the UI so the script is no longer required.

**Comment by chrisroos** [comment]
I've opened PR #981 to address this issue.

**Comment by chrisroos** [comment]
PR #981 has been merged so this is all done. Closing.
