### ISSUE TITLE
Extract API adapters from exporters

### ISSUE THREAD

**Issue by chrislo** [alphagov/manuals-publisher#996]
The idea is that there will be a single adapter class for each of the external APIs that the application needs to interact with. These classes should be the **only** way that application code interacts with these external services. The method signatures, method return values and exceptions raised by methods on these classes should all be in terms of the application's own domain model and **not** the classes or concepts specific to the external API, i.e. they should abstract the application away from knowing anything about the underlying external API. The choice of the word "Adapter" is taken from the [Ports and Adapters Pattern][1].

[1]: http://alistair.cockburn.us/Hexagonal+architecture

**Comment by floehopper** [comment]
The following were motivated by this issue:

* [Introduce SearchIndexAdapter](https://github.com/alphagov/manuals-publisher/pull/1034)
* [Collapse formatters and RummagerIndexer into SearchIndexAdapter](https://github.com/alphagov/manuals-publisher/pull/1046)

**Comment by floehopper** [comment]
The following PRs were also motivated by this issue:

* [Introduce OrganisationsAdapter & inline OrganisationFetcher into it](https://github.com/alphagov/manuals-publisher/pulls/1053)
* [Extract version_type methods for Manual and Section](https://github.com/alphagov/manuals-publisher/pulls/1077)
* [Simplify PublishingApiUpdateTypes](https://github.com/alphagov/manuals-publisher/pulls/1078)
* [Use PublishingAdapter in CliManualDeleter instead of using Publishing API directly](https://github.com/alphagov/manuals-publisher/pulls/1110)

**Comment by floehopper** [comment]
The work on this is largely completed, but there are still three places where the Publishing API is used directly, i.e. not via the `PublishingAdapter`:

* [`ManualRelocator`](https://github.com/alphagov/manuals-publisher/blob/4d6f8b02f034b2e39746b22dae658c408b640220/lib/manual_relocator.rb)
* [`MarkedSectionDeleter`](https://github.com/alphagov/manuals-publisher/blob/4d6f8b02f034b2e39746b22dae658c408b640220/lib/marked_section_deleter.rb)
* [`DuplicateDraftDeleter`](https://github.com/alphagov/manuals-publisher/blob/4d6f8b02f034b2e39746b22dae658c408b640220/lib/duplicate_draft_deleter.rb)

The need for some of these might be reduced/removed by the following PRs:

* [Avoid persisting updated sections when saving to Publishing API fails](https://github.com/alphagov/manuals-publisher/pull/1141)
* [Avoid persisting new manuals when saving to Publishing API fails](https://github.com/alphagov/manuals-publisher/pull/1148)

So I'm planning to open specific issues for the three classes still using the Publishing API directly and close this issue.

**Comment by floehopper** [comment]
I've now opened the following issues to capture the remaining work for this issue:

* #1161
* #1162
* #1163
